config/routes.rb
Rails.application.routes.draw do
  resources :robots, :attachments

  root 'robots#index'
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :robot
end

app/models/robot.rb
class Robot < ActiveRecord::Base
  has_many :attachments
  validates :name, :job, :height, :weight, :color, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController
  def index
    @robots = Robot.all
  end

  def show
    @robot = Robot.find(params[:id])
  end

  def new
    @robot = Robot.new
  end

  def edit
    @robot = Robot.find(params[:id])
  end

  def create
    @robot = Robot.new(robot_params)

    if @robot.save
      flash[:success] = "Robot created!"
      redirect_to @robot
    else
      render 'new'
    end
  end

  def update
    @robot = Robot.find(params[:id])

    if @robot.update(robot_params)
      flash[:success] = "Robot updated!"
      redirect_to @robot
    else
      render 'edit'
    end
  end

  def destroy
    @robot = Robot.find(params[:id])
    @robot.destroy
    flash[:success] = "Robot deleted!"
    redirect_to robots_path
  end

  private

  def robot_params
    params.require(:robot).permit(:name, :job, :height, :weight, :color)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/robots_helper.rb
module RobotsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}
    %title ProBot
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %body
      = render 'navbar'
      - if flash[:success]
        .alert.alert-success= flash[:success]
      .container
        = yield

app/views/robots/_errors.html.haml
.panel.panel-danger
  .panel-heading
    = "#{pluralize(@robot.errors.count, "error")} prohibited this robot from being saved:"
  .panel-body
    - @robot.errors.full_messages.each do |msg|
      %li= msg

app/views/robots/_form.html.haml
- if @robot.errors.any?
  = render 'errors'

= form_for @robot, role: 'form', class: 'form-horizontal' do |f|
  .form-group#robot_name
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :name, class: 'form-control'
  .form-group#robot_job
    = f.label :job, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :job, class: 'form-control'
  .form-group#robot_height
    = f.label :height, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :height, class: 'form-control', placeholder: 'feet'
  .form-group#robot_weight
    = f.label :weight, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :weight, class: 'form-control', placeholder: 'pounds'
  .form-group#robot_color
    = f.label :color, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :color, class: 'form-control'
  .btn.btn_success#robot_submit
    = f.submit

.btn.btn_default#back_link_new= link_to 'Back', robots_path

app/views/robots/_navbar.html.haml
%nav.navbar.navbar-default{role: "navigation"}
  .navbar-header
    .navbar-brand= link_to "ProBot", "/"
  - unless params[:action] == "new"
    %div
      %ul.nav.navbar-nav
        %li.active#new_robot_link= link_to "New Robot", new_robot_path

app/views/robots/edit.html.haml
%h1 Edit Robot

= render 'form'

app/views/robots/index.html.haml
.header_container
  %h1 ProBot
  %h5 an adaptive assistant for any application
%table.table.table-hover
  %tr
    %th Name
    %th Job
  -@robots.each do |robot|
    %tr
      %td= link_to robot.name, robot_path(robot)
      %td= robot.job
      %td.btn.btn-xs.btn-info= link_to 'Edit', edit_robot_path(robot)
      %td.btn.btn-xs.btn-danger= link_to 'Delete', robot_path(robot),                |
           method: :delete, data: { confirm: 'Are you sure?' } |

app/views/robots/new.html.haml
%h1 New Robot

= form_for @robot do |f|
  %p
    = f.label :name
    = f.text_field :name
  %p
    = f.label :job
    = f.text_field :job
  %p
    = f.label :height
    = f.text_field :height
  %p
    = f.label :weight
    = f.text_field :weight
  %p
    = f.label :color
    = f.text_field :color
  %p
    = f.submit

app/views/robots/show.html.haml
.panel.panel-default#name_panel
  .panel-heading Name
  .panel-body= @robot.name
.panel.panel-default
  .panel-heading Job
  .panel-body= @robot.job
.panel.panel-default
  .panel-heading Height
  .panel-body= @robot.height.to_s + " ft"
.panel.panel-default
  .panel-heading Weight
  .panel-body= @robot.weight.to_s + " lbs"
.panel.panel-default
  .panel-heading Color
  .panel-body= @robot.color

.btn.btn-default#back_link= link_to 'Back', robots_path
.btn.btn-default= link_to 'Edit', edit_robot_path